---

apiVersion: apps/v1
kind: Deployment  
metadata:
  name: 
  namespace: 
  labels:         
    app: 
spec:
  selector:
    matchLabels:        
      app: 
  strategy:
    type: Recreate
  template:       
    metadata:
      labels:   
        app: 
    spec:                         
      containers:
      - image:    
        name: 
        env:                     
        - name: MYSQL_ROOT_PASSWORD 
          valueFrom:              
            configMapKeyRef:
              name: 
              key: password
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: database
        ports:
        - containerPort: 3306          
          name: mysql
        

          