apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: flotech-system
spec:
  storageClassName: standard
  capacity:
    storage: 250Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
  persistentVolumeReclaimPolicy: Retain