apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: flotech-system
  labels:
    app: fth-pub-mysql
spec:
  type: ClusterIP
  selector:
    app: fth-pub-mysql  
  ports:
  - port: 3306
    targetPort: 3306