---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  -sms
  namespace:   -system 
spec:
  replicas: 1
  selector:
    matchLabels:
      app:   - -sms
  template:
    metadata:
      name:  -sms 
      labels:
        app:   - -sms
    spec:
      containers:
      - name:  -sms
        image:  #Input
        ports:
        - containerPort: 3307 
        env:
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name:  -mysql-configmap
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            configMapKeyRef:
              name:  -mysql-configmap
              key: password
        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: hostname-config
              key: mysql_host

---
apiVersion: v1
kind: Service
metadata:
  name:  -sms-service
  namespace:   -system 
  labels:
    app:   - -sms
spec:
  type: LoadBalancer
  selector:
    app:   - -sms  
  ports:
    - name:  -sms
      port: 3307
      targetPort: 3307
      protocol: TCP