---
apiVersion: v1
kind: Service
metadata:
  name: python-app-svc
  labels:
    app: python-app
spec:
  type: LoadBalancer
  selector:
    app: python-app  
  ports:
    - name: python-app
      port: 3333
      targetPort: 3333
      protocol: TCP